trigger: none
  # branches:
  #   include:
  #     - main
  #     - feature/*

pool: practice-pipeline-pool

parameters:
  - name: envs
    displayName: Select Environment
    type: string
    default: dev
    values:
      - dev
      - prod

variables:
  # - name: workingDir
  #   value: ${{ format('{0}/envs/{1}', variables['System.DefaultWorkingDirectory'], parameters.envs) }}

  # - name: SVC
  #   value: practice-connection

  # - name: storageAccount
  #   value: tfstatestg${{ parameters.envs }}001

  # - name: tfstateKey
  #   value: ${{ parameters.envs }}.terraform.tfstate

  - group: MyVarGroup


stages:
  - stage: Build
    displayName: "Build"
    jobs:
      - job: initvalidateandplanjob
        displayName: "Terraform Init, Validate & Plan"
        steps:
          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDir)'
              backendServiceArm: '$(SVC)'
              backendAzureRmStorageAccountName: '$(storageAccount)'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '$(tfstateKey)'

          - task: TerraformTask@5
            displayName: "Terraform Validate"
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(workingDir)'

          - task: TerraformTask@5
            displayName: "Terraform Plan"
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(workingDir)'
              environmentServiceNameAzureRM: '$(SVC)'
              commandOptions: '-detailed-exitcode -lock=false -var-file="terraform.tfvars"'


  - stage: Scanning
    displayName: Scanning
    dependsOn: Build
    jobs:
      - job: multiplescans
        displayName: Multiple Scans
        steps:
          - task: PowerShell@2
            displayName: tfsec scan
            continueOnError: true
            inputs:
              targetType: 'inline'
              script: 'tfsec .'

          # - task: tfsec@1
          #   displayName: tfsec scan
          #   continueOnError: true
          #   inputs:
          #     version: 'v1.26.0'
          #     dir: '$(workingDir)'

          - task: PowerShell@2
            displayName: checkov scan
            continueOnError: true
            inputs:
              targetType: 'inline'
              script: 'checkov -d .'
              workingDirectory: '$(workingDir)'

          - task: PowerShell@2
            displayName: tflint scan
            continueOnError: true
            inputs:
              targetType: 'inline'
              script: 'tflint -d .'
              workingDirectory: '$(workingDir)'


  - stage: ApprovalandDeploy
    displayName: Approval & Deploy to Azure
    dependsOn: Build
    jobs:
      - job: manualvalidation
        displayName: "Manual Validation"
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'adhiraaj22@gmail.com'
              approvers: 'adhiraaj22@gmail.com'

      - job: applyjob
        displayName: "Terraform Apply"
        dependsOn: manualvalidation
        steps:
          - task: TerraformTask@5
            displayName: "Terraform Init (Deploy Stage)"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDir)'
              backendServiceArm: '$(SVC)'
              backendAzureRmStorageAccountName: '$(storageAccount)'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '$(tfstateKey)'

          - task: TerraformTask@5
            displayName: "Terraform Apply"
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(workingDir)'
              commandOptions: '-auto-approve -var-file="terraform.tfvars"'
              environmentServiceNameAzureRM: '$(SVC)'
