trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  name: practice-pipeline-pool

variables:
  svc: practice-connection
  stgname: tfstatestgdev001
  containername: tfstate
  statefile: dev.terraform.tfstate
  workingDir: $(System.DefaultWorkingDirectory)/envs/dev

stages:

  - stage: Build
    jobs:
      - job: terraforminitandplan
        displayName: Terraform Init, Validate & Plan

      - job: TerraformInstall
        displayName: Terraform Install
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: latest

      - job: TerraformInitValidatePlan
        displayName: Terraform Init, Validate & Plan
        steps:
          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: azurerm
              command: init
              workingDirectory: $(workingDir)
              backendServiceArm: $(svc)
              backendAzureRmStorageAccountName: $(stgname)
              backendAzureRmContainerName: $(containername)
              backendAzureRmKey: $(statefile)

          - task: TerraformTask@5
            displayName: Terraform Validate
            inputs:
              provider: azurerm
              command: validate
              workingDirectory: $(workingDir)

          - task: TerraformTask@5
            displayName: Terraform Plan
            inputs:
              provider: azurerm
              command: plan
              workingDirectory: $(workingDir)
              environmentServiceNameAzureRM: $(svc)

  - stage: Release
    dependsOn: Build
    jobs:

      - job: TfLint
        displayName: TFLint Scan
        pool:
          name: practice-pipeline-pool
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo "Installing TFLint..."
                curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
                echo "Running TFLint..."
                tflint --init
                tflint $(workingDir)

      - job: ManualValidation
        displayName: Manual Approval
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: adhiraaj22@gmail.com

      - job: TerraformApply
        displayName: Terraform Apply
        dependsOn: ManualValidation
        pool:
          name: practice-pipeline-pool
        steps:
          - task: TerraformTask@5
            displayName: Terraform Init (Apply Stage)
            inputs:
              provider: azurerm
              command: init
              workingDirectory: $(workingDir)
              backendServiceArm: $(svc)
              backendAzureRmStorageAccountName: $(stgname)
              backendAzureRmContainerName: $(containername)
              backendAzureRmKey: $(statefile)

          - task: TerraformTask@5
            displayName: Terraform Apply
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: $(workingDir)
              environmentServiceNameAzureRM: $(svc)
