trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  name: practice-pipeline-pool

variables:
  svc: practice-connection
  stgname: tfstatestgdev001
  containername: tfstate
  statefile: dev.terraform.tfstate
  workingDir: $(System.DefaultWorkingDirectory)/envs/dev

stages:

# ---------------------------------------------------
# BUILD STAGE – INIT, VALIDATE, PLAN, SAVE ARTIFACT
# ---------------------------------------------------
- stage: Build
  displayName: "Terraform Build (Init, Validate, Plan)"
  jobs:

    - job: TerraformInstall
      displayName: Terraform Install
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: latest

    - job: TerraformPlanJob
      displayName: Terraform Init, Validate & Plan
      dependsOn: TerraformInstall
      steps:

        # Terraform Init -----------------------------
        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: azurerm
            command: init
            workingDirectory: $(workingDir)
            backendServiceArm: $(svc)
            backendAzureRmStorageAccountName: $(stgname)
            backendAzureRmContainerName: $(containername)
            backendAzureRmKey: $(statefile)

        # Terraform Validate --------------------------
        - task: TerraformTask@5
          displayName: Terraform Validate
          inputs:
            provider: azurerm
            command: validate
            workingDirectory: $(workingDir)

        # Terraform Plan (output saved) ---------------
        - task: TerraformTask@5
          displayName: Terraform Plan
          inputs:
            provider: azurerm
            command: plan
            workingDirectory: $(workingDir)
            environmentServiceNameAzureRM: $(svc)
            commandOptions: "-out=tfplan -lock-timeout=120s"

        # Publish Plan Artifact ------------------------
        - publish: $(workingDir)/tfplan
          artifact: tfplan-artifact
          displayName: "Publish Terraform Plan Artifact"


# ---------------------------------------------------
# RELEASE STAGE – MANUAL APPROVAL → APPLY
# ---------------------------------------------------
- stage: Release
  displayName: "Terraform Release (Manual Approval + Apply)"
  dependsOn: Build
  jobs:

    # Manual Approval -------------------------------
    - job: ManualValidation
      displayName: "Manual Approval Before Apply"
      pool: server
      steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: adhiraaj22@gmail.com

    # Terraform Apply -------------------------------
    - job: TerraformApply
      displayName: Terraform Apply
      dependsOn: ManualValidation
      pool:
        name: practice-pipeline-pool
      steps:

        # Download plan artifact ---------------------
        - download: current
          artifact: tfplan-artifact
          displayName: "Download Terraform Plan Artifact"

        # Wait for backend lock to release -----------
        - script: |
            echo "Waiting for Terraform backend lock to release..."
            sleep 15
          displayName: "Wait for Lock Release"

        # Terraform Init -----------------------------
        - task: TerraformTask@5
          displayName: Terraform Init (Apply Stage)
          inputs:
            provider: azurerm
            command: init
            workingDirectory: $(workingDir)
            backendServiceArm: $(svc)
            backendAzureRmStorageAccountName: $(stgname)
            backendAzureRmContainerName: $(containername)
            backendAzureRmKey: $(statefile)

        # Terraform Apply (using saved tfplan) -------
        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: azurerm
            command: apply
            workingDirectory: $(workingDir)
            environmentServiceNameAzureRM: $(svc)
            commandOptions: "tfplan -auto-approve -lock-timeout=120s"
